### ISSUE TITLE
[bug] GPU builds of any consumer fail to link: getAllGPUMemoryInfo is defined with external linkage

### ISSUE THREAD

**Issue by tinswzy** [zilliztech/woodpecker#332]
## Summary

`common/hardware/gpu_mem_info_cuda.go` defines a C function in its cgo preamble **without `static`**, so the symbol has external linkage. Any consumer that builds with the `cuda` tag and also defines a function of that name fails at link time:

```
multiple definition of `getAllGPUMemoryInfo'
```

Milvus is exactly that consumer, and its GPU builds on 2.6 are currently broken by this.

## The defect

```c
// common/hardware/gpu_mem_info_cuda.go:19
int getAllGPUMemoryInfo(GPUMemoryInfo** infos) {
```

cgo compiles the preamble into the object file it generates for this package. A non-`static` function definition there is an exported symbol, so it collides with any other definition of the same name in the final link.

This package is a copy of Milvus's `pkg/util/hardware` — same filenames, same contents, the Milvus copyright header still on several of them. Milvus's own copy gets it right:

```c
// milvus pkg/util/hardware/gpu_mem_info_cuda.go:19
static int getAllGPUMemoryInfo(GPUMemoryInfo** infos) {
```

The keyword was not dropped in the copy, though. Milvus's own copy was not `static` either when this package was copied from it in `14e53bb` (2026-01-31) -- the C preamble is byte-identical to Milvus's file as of `38881bf59`. Milvus hit the resulting collision on its own master branch ([milvus-io/milvus#49368](https://github.com/milvus-io/milvus/issues/49368), "duplicated method name: getAllGPUMemoryInfo") and made its copy `static` in [milvus-io/milvus#49383](https://github.com/milvus-io/milvus/pull/49383) (2026-04-27). Nothing propagated that back here. `static` is the standard form for a function defined in a cgo preamble, and it is what confines the symbol to one translation unit.

The `GPUMemoryInfo` typedef above it is fine: a type definition emits no symbol.

## Why nobody noticed

Both GPU files are behind `//go:build cuda`. Nothing compiles them unless the consumer builds with that tag, so every non-GPU build — including every build in this repository — links cleanly.

**This repository has no cuda build at all**: no workflow and no Makefile target passes the tag, so the file has never been compiled in our own CI since the day it was added. It only ever comes alive in a consumer's GPU build, which is why the breakage surfaces there and not here.

## How long it has been there

Since the file was first added, in `14e53bb` ("refactor(metrics): overhaul metrics system with new instrumentation and dependency upgrades"), which first shipped in **v0.1.16**. It has been non-`static` in every tag from v0.1.16 through v0.1.43.

It stayed invisible on the branches that carry Milvus's fix. Two external definitions are needed to collide, and since #49383 Milvus master and 3.0 contribute none -- their copy is `static` -- so ours is the only one and the link succeeds. That is why master has been building GPU images against woodpecker v0.1.25+ ever since.

**Milvus 2.6 never received #49383.** Its copy is still non-`static`, and it was pinned to a `v0.1.14-...` pseudo-version that predates this file entirely, so it had one external definition and linked. Bumping 2.6 to v0.1.42 (milvus-io/milvus#50201) crossed v0.1.16 for the first time, added the second definition, and the collision Milvus already fixed once came back on that branch alone.

So the blast radius is narrower than it looks: the currently broken build is Milvus 2.6, and it is broken because it is missing a fix master has had since April. The open bumps to v0.1.43 (milvus-io/milvus#53468, milvus-io/milvus#53470) target master and 3.0, which both carry #49383, so they are not affected.

Fixing it here is still worth doing -- it removes the exported symbol entirely, so no consumer can collide with us regardless of what their own copy looks like -- but it is not the fastest route to a green 2.6 GPU build. Cherry-picking #49383's one line onto 2.6 needs no woodpecker release.

## Fix

Delete both GPU files and the test that covered the stub -- see #333.

Adding `static` was the first proposal, and it is the weaker one: it stops the symbol colliding but keeps a CUDA cgo compilation unit in a package every consumer links, for code nothing calls. Nothing in woodpecker uses these helpers and nothing ever has -- outside `common/hardware` the repo has zero references to `GPUMemoryInfo` or `GetAllGPUMemoryInfo`, the only caller was `Test_GetAllGPUMemoryInfo` asserting the non-CUDA stub errors, and no workflow, Makefile target or Dockerfile passes `-tags cuda`. They are here because the whole package was copied from Milvus, which does have a real caller (`internal/querynodev2/segments/segment_loader.go`); a WAL over object storage does not.

Deleting removes the symbol instead of hiding it, and settles the CI question below on its own: after it, `go build -tags cuda ./...` needs no CUDA toolchain and `go list -tags cuda` reports no cgo files for the package, so there is no uncompiled build left to rot.

One trap: both files have to go together. `gpu_mem_info.go` is `//go:build !cuda`, so deleting only the CUDA file would leave the package with no definition at all under the tag -- breaking consumers' GPU builds harder than the collision does.

## Worth considering separately

A build that no CI ever performs cannot stay correct by luck. Deleting the files removes this instance, but nothing stops the next wholesale copy from Milvus reintroducing the shape. A test that scans cgo preambles for non-`static` function definitions would catch it without needing a CUDA toolchain in the image.
